#!/bin/sh

if [ "$method" = "status" ]; then
	. /usr/share/libubox/jshn.sh
	echo "Content-type: application/json"
	echo
json_init
json_add_string mode "$(nodeadm mode)"
json_dump
	exit;
fi
header
cat << EOF
<h1>Mesh</h1>
<input type="button" class="btn btn-primary" id="gateway" value="Gateway" />
<input type="button" class="btn btn-primary" id="standalone" value="Standalone" />
<input type="button" class="btn btn-primary" id="client" value="Client" />
&lt;-- This is the current status, but they don't do anything yet
<h1>Disk</h1>
<pre>
$(df -h /overlay)
</pre>
<h1>Env</h1>
<pre>
$(env)
</pre>
EOF
footer
cat << EOF
<script>
function getstatus() {
	$.getJSON('/admin/status/', function(data) {
		\$("#" + data.mode.toLowerCase()).removeClass("btn-primary").addClass("btn-success");
	});
}
\$(function() {
	\$(".btn").click(function() {
		console.log(\$(this).val());
	});
	getstatus();
});
</script>
EOF
