#!/bin/ash
# something to redirect to / if we're not sourced from there
# we handle all methods, don't judge
header
cat << EOF
	<!-- Main hero unit for a primary marketing message or call to action -->
	<div class="jumbotron">
		<h1>Don't Panic</h1>
		<p>You're on a wireless mesh setup to provide communication with other people in the area.</p>
		<p><a href="/about/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
	</div>

	<!-- Example row of columns -->
	<div class="row">
		<div class="span4">
			<h2>Message Board</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			<p><a class="btn" href="/board/">View details &raquo;</a></p>
		</div>
		<div class="span4">
			<h2>Live Webchat</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
			<p><a class="btn" href="/chat/">View details &raquo;</a></p>
		</div>
		<div class="span4">
			<h2>Wiki?</h2>
			<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
			<p><a class="btn" href="/wiki/">View details &raquo;</a></p>
		</div>
	</div>
EOF
footer
