#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org 

START=99
STOP=99
start() {
	[ -d /www ] || mkdir /www
	service_start /usr/sbin/httpd -c /etc/httpd.conf
}

stop() {
	service_stop /usr/sbin/httpd
}
